on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - run: npm i
      - run: npm run compile
