on: [pull_request_review]
jobs:
  build:
    runs-on: node:lts
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
      - run: node -v && npm -v
      - run: npm install
      - run: npm test
